insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10001', 'Olive Sheath Dress', 'ModCloth', '59.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10002', 'Joys A-Line Dress', 'ModCloth', '99.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10003', 'Ivory Tank Top', 'ModCloth', '39.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10004', 'Photoshoot Sweater', 'ModCloth', '59.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10005', 'Jeans Overalls', 'ModCloth', '59.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10006', 'Knit Tunic', 'J Jill', '59.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10007', 'Boatneck Tee', 'Ann Taylor', '24.99');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10008', 'Sweater Dress', 'Venus', '34.50');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10009', 'Plaid Shirt', 'Ralph Lauren', '34.00');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10010', 'Wool Reefer Coat', 'Nordstrom', '220.00');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10011', 'Midi Dress', 'Tom Ford', '12450.00');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10012', 'Duster Sweater', 'Venus', '34.00');
insert into bettysinventory.products (product_id, product_name, product_manufacturer, product_price) values ('10013', 'Dream Dress', 'Historical Clothing', '162.00');
